### ISSUE TITLE
Add support for the Industrial PTC Bricklet

### ISSUE THREAD

**Issue by glopesdev** [emotional-cities/tinkerforge#20]
Tinkerforge details: https://www.tinkerforge.com/en/doc/Hardware/Bricklets/Industrial_PTC.html

**Comment by RoboDoig** [comment]
Already exists as IndustrialPTC - is there a bug with implementation?

**Comment by RoboDoig** [comment]
Was this supposed to be add support for BrickletPTC?

**Comment by glopesdev** [comment]
Oops, no you are totally right, just forgot about it while adding all the issues.
